### ISSUE TITLE
Unable to make https calls using this client . 

### ISSUE THREAD

**Issue by bpillai** [americanexpress/nodes#33]
The client seems to be using httpurlconnection to make the graph ql api calls . This restricts making calls to https .

**Comment by chemdrew** [comment]
Can you please provide the error message? httpurlconnection is still capable of making https calls, it is doing so in `samples/kotlin-sample/src/main/kotlin/Main.kt` as well as `samples/scala-sample/src/main/scala/Main.scala` when querying against the GitHub v4 open api.

**Comment by bpillai** [comment]
Also is there a reason to use httpUrlConnection over httpsUrlConnection ?

**Comment by bpillai** [comment]
I want to be abe to load a keystore file while opening the connection . If thhis client is used in a serverless app , then to be able to call a https which mandates a cert we would have to load it while opening the connection . I believe that is currently not possible .

**Comment by chemdrew** [comment]
Hi @bpillai, the reason I chose httpUrlConnection over httpsUrlConnection is because I wanted the library to support http as well as https ([see this](https://stackoverflow.com/questions/3920419/difference-between-urlconnection-httpurlconnection-and-httpsurlconnection)). Your error looks unrelated to this library and more of an issue with loading your keystore into the jvm. Loading your keystore can be done in many ways based on your application and how it is run, you can find many articles and posts on doing this each way. Closing this issue out.
